Milestone 3 - Connect Redux Actions
Zubenna/my-bookstore-project pull request #3
Opened 2021-03-31 23:00 UTC by Zubenna

2021-04-01 13:46 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @Zubenna, congratulations on this project :+1: The README and the PR look professional :+1: The code is clean :100: The BookFOrm component is implemented well :100: The Book component stays presentational and attaches the "remove book" to the click event :slightly_smiling_face: 
Also, remember to check the microverse group linter files and make sure it is the same as the one you are using. [requirements](https://github.com/microverseinc/linters-config/blob/master/react-redux/.eslintrc.json)

However, before we can approve the project :+1: Let us kindly address the comments below

[Optional]
- Let us kindly add validation so a user can not save empty data, since it will be cost-effective and slow performance


Once these are resolved, kindly submit another code review request :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-04-01 13:46 UTC, addod19 commented on src/containers/BooksList.js
> +
- We were asked to implement handleRemoveBook. Let us kindly implement the handleRemoveBook function

2021-04-01 13:46 UTC, addod19 commented on src/containers/BooksList.js
> +        <Book key={book.id} book={book} removeBook={removeBook} />
Also, we need to pass the handleRemoveBook function to the Book component

2021-04-02 09:05 UTC, teekaytech approved these changes
# Status: Approved :green_circle: 

### Congratulations @Zubenna :tada: :clinking_glasses: 

_**Thank you for fixing the issues raised by the last reviewer.**_

**This project has passed all the mandatory requirements :clap: 
It is therefore approved :heavy_check_mark:**

**Comment(s)**
- Against your next milestone, please fix the broken `MIT` license link on your Readme.
- Do not forget to push your changes to deployment.
- If your project does not have test cases, kindly remove the `Testing` section of the Readme.

Again, congratulations, you can now start the next milestone.
Do not forget to fill the project completion form, as this is important for your weekly progress score.

**_Good luck with your next task._**

* * * 
**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

2021-04-02 14:29 UTC, merged